### ISSUE TITLE
AttributeError: Can't pickle local object 'SubPolicy.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by PangJian123** [open-mmlab/OpenUnReID#1]
how can i fix it, thank u

==========
Args:Namespace(config='source_pretrain/config.yaml', launcher='none', resume_from=None, set_cfgs=None, tcp_port='5017', work_dir='source_pretrain/market1501')
==========
cfg.LOCAL_RANK: 0
cfg.DATA_ROOT: /home/pj/re-id/data
cfg.LOGS_ROOT: ../logs

cfg.MODEL = edict()
cfg.MODEL.backbone: resnet50
cfg.MODEL.pooling: gem
cfg.MODEL.embed_feat: 0
cfg.MODEL.dropout: 0.0
cfg.MODEL.dsbn: False
cfg.MODEL.sync_bn: True
cfg.MODEL.samples_per_bn: 64
cfg.MODEL.mean_net: False
cfg.MODEL.imagenet_pretrained: True
cfg.MODEL.source_pretrained: None

cfg.DATA = edict()
cfg.DATA.height: 256
cfg.DATA.width: 128
cfg.DATA.norm_mean: [0.485, 0.456, 0.406]
cfg.DATA.norm_std: [0.229, 0.224, 0.225]

cfg.DATA.TRAIN = edict()
cfg.DATA.TRAIN.is_autoaug: True
cfg.DATA.TRAIN.is_flip: True
cfg.DATA.TRAIN.flip_prob: 0.5
cfg.DATA.TRAIN.is_pad: True
cfg.DATA.TRAIN.pad_size: 10
cfg.DATA.TRAIN.is_blur: False
cfg.DATA.TRAIN.blur_prob: 0.5
cfg.DATA.TRAIN.is_erase: False
cfg.DATA.TRAIN.erase_prob: 0.5
cfg.DATA.TRAIN.is_mutual_transform: False
cfg.DATA.TRAIN.mutual_times: 2

cfg.TRAIN = edict()
cfg.TRAIN.seed: 1
cfg.TRAIN.deterministic: True

cfg.TRAIN.datasets = edict()
cfg.TRAIN.datasets.market1501: trainval
cfg.TRAIN.unsup_dataset_indexes: None
cfg.TRAIN.epochs: 120
cfg.TRAIN.iters: 200

cfg.TRAIN.LOSS = edict()

cfg.TRAIN.LOSS.losses = edict()
cfg.TRAIN.LOSS.losses.cross_entropy: 1.0
cfg.TRAIN.LOSS.losses.softmax_triplet: 1.0
cfg.TRAIN.LOSS.margin: 0.0
cfg.TRAIN.val_dataset: market1501
cfg.TRAIN.val_freq: 40

cfg.TRAIN.SAMPLER = edict()
cfg.TRAIN.SAMPLER.num_instances: 4
cfg.TRAIN.SAMPLER.is_shuffle: True

cfg.TRAIN.LOADER = edict()
cfg.TRAIN.LOADER.samples_per_gpu: 16
cfg.TRAIN.LOADER.workers_per_gpu: 4

cfg.TRAIN.OPTIM = edict()
cfg.TRAIN.OPTIM.optim: adam
cfg.TRAIN.OPTIM.lr: 0.00035
cfg.TRAIN.OPTIM.weight_decay: 0.0005

cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.lr_scheduler: warmup_multi_step
cfg.TRAIN.SCHEDULER.stepsize: [40, 70]
cfg.TRAIN.SCHEDULER.gamma: 0.1
cfg.TRAIN.SCHEDULER.warmup_factor: 0.01
cfg.TRAIN.SCHEDULER.warmup_steps: 10

cfg.TEST = edict()
cfg.TEST.datasets: ['market1501']

cfg.TEST.LOADER = edict()
cfg.TEST.LOADER.samples_per_gpu: 32
cfg.TEST.LOADER.workers_per_gpu: 4
cfg.TEST.dist_metric: euclidean
cfg.TEST.norm_feat: True
cfg.TEST.dist_cuda: True
cfg.TEST.rerank: False
cfg.TEST.search_type: 0
cfg.TEST.k1: 20
cfg.TEST.k2: 6
cfg.TEST.lambda_value: 0.3
cfg.launcher: none
cfg.tcp_port: 5017
cfg.work_dir: ../logs/source_pretrain/market1501
cfg.total_gpus: 1
The training is in a fully-supervised manner with 1 dataset(s) (['market1501'])
=> Loaded trainval from Market1501
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
    751 |    12936 |         6
  ----------------------------
=> Loaded the Joint Training Dataset
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
    751 |    12936 |         6
  ----------------------------
/home/pj/OpenUnReID-master/openunreid/utils/torch_utils.py:69: UserWarning: unexpected keys in checkpoint: {'fc.weight', 'fc.bias'}
  warnings.warn("unexpected keys in checkpoint: {}".format(unexpected_keys))
/home/pj/OpenUnReID-master/openunreid/models/builder.py:255: UserWarning: Sync BN is switched off, since the program is running without DDP
  warnings.warn(
=> Loaded val from Market1501
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
    150 |     2257 |         6
  ----------------------------
Traceback (most recent call last):
  File "source_pretrain/main.py", line 140, in <module>
    main()
  File "source_pretrain/main.py", line 122, in main
    runner.run()
  File "/home/pj/OpenUnReID-master/openunreid/apis/runner.py", line 94, in run
    self.train()
  File "/home/pj/OpenUnReID-master/openunreid/apis/runner.py", line 171, in train
    self.train_loader.new_epoch(self._epoch)
  File "/home/pj/OpenUnReID-master/openunreid/data/utils/dataset_wrapper.py", line 89, in new_epoch
    self.iter = iter(self.loader)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/pj/anaconda3/envs/reid/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SubPolicy.__init__.<locals>.<lambda>'

**Comment by yxgeee** [comment]
Please refer to https://github.com/open-mmlab/OpenUnReID/blob/master/docs/INSTALL.md#install-openunreid (**f**)

**Comment by zhangp14** [comment]
another choice:

change `workers_per_gpu=2` to `workers_per_gpu=0`   in  OpenUnReID/tools/source_pretrain/config.yaml


Ref: [num_workers=0](https://github.com/rusty1s/pytorch_geometric/issues/366). Still works on Ubuntu16.04
