### ISSUE TITLE
训练时候的小问题?

### ISSUE THREAD

**Issue by huang1997214** [open-mmlab/OpenUnReID#10]
您好请问您遇到过这个问题吗:
在训练的时候,每经过固定的iteration后会卡住一段时间（似乎这个频率与数据集大小及iteration有关，我有一个试验是每320个iteration卡一次，另一个试验每20个iteration会卡一次）。
我是用集群跑的，4块卡
samples_per_gpu: 32
workers_per_gpu: 2
320卡一次的试验: 494354张image, 11968 iteration
20次卡一次的试验: 227790张image, 5514 iteration
麻烦您啦!

**Comment by yxgeee** [comment]
看样子像是workers_per_gpu的问题，要不尝试将workers_per_gpu设大一点呢。你看看你的机器上CPU一共有多少核，尽量全部用上。

**Comment by huang1997214** [comment]
好的好的，我试试看。谢谢您啦!

**Comment by yxgeee** [comment]
我也碰到过类似的问题，每过一些iteration会有一次超长的读数据时间，后来我用大点的workers_per_gpu（比如4），然后换了个集群，就没出现了，所以我后来就没有去管这个。但是我觉得可能还是代码哪里优化的不到位，你如果找到问题的话可以pull个request。感谢

**Comment by huang1997214** [comment]
好的，我之后如果有何发现一定和您说。

**Comment by huang1997214** [comment]
您好，我把workers_per_gpu设置成0之后好像就再没有出现过那个问题了。
