### ISSUE TITLE
距离选择的问题。

### ISSUE THREAD

**Issue by huang1997214** [open-mmlab/OpenUnReID#12]
您好有两个关于距离的问题想再问下您。
1. Jaccard距离效果会比其他两个好很多吗？
2. 因为想在计算Jaccard距离的时候压缩下内存(避免出现N * N)。如果k2平均的那一步不去作，会对结果有很大影响吗?
![WeChat Work Screenshot_20200828104857](https://user-images.githubusercontent.com/45142783/91515599-1e9a3480-e91c-11ea-8b69-295a9e108061.png)
麻烦您啦!

**Comment by yxgeee** [comment]
影响挺大的。欧氏距离对dbscan里eps参数（intra-cluster distance）的敏感性比较高，不好调。

**Comment by huang1997214** [comment]
好的好的，谢谢您啦!

**Comment by huang1997214** [comment]
不好意思，想问下您之前三个欧氏距离的eps取的分别是多少呢。因为还是要跑一下欧氏距离的试验，想参考一下您之前的参数。麻烦您啦!

**Comment by yxgeee** [comment]
我不记得了🤦‍♀️ 应该是比现在的eps要小，但是我记得我跑的fail了

**Comment by huang1997214** [comment]
我调调看看，谢谢您啦!
