### ISSUE TITLE
SpCL Train_step的问题

### ISSUE THREAD

**Issue by huang1997214** [open-mmlab/OpenUnReID#14]
![WeChat Work Screenshot_20200901174113](https://user-images.githubusercontent.com/45142783/91835063-75d13980-ec7b-11ea-8da8-00d302ae33f7.png)
您好，想问下您这里id是否代表label.还想问下ind代表什么.
麻烦您啦!

**Comment by yxgeee** [comment]
你好，id代表label，ind代表该image在dataset里的位置（index）
