### ISSUE TITLE
关于CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 5.80 GiB total capacity; 4.98 GiB already allocated; 4.25 MiB free; 9.66 MiB cached)

### ISSUE THREAD

**Issue by GJTNB** [open-mmlab/OpenUnReID#17]
我的硬件配置是1660ti，6g显存，训练命令是  GPUS=1 bash dist_train.sh CycleGAN mark_duck，我修改了配置文件里的iter次数，还是显示内存不足，请问是硬件配置不行吗？但是我跑cyclegan作者的模型是可以训练的。

**Comment by yxgeee** [comment]
你好，请修改这里`samples_per_gpu`（cyclegan原代码的话这里应该是1，但是我为了训练更快修改了一下，你可以根据自己的硬件情况酌情减小这个值）
https://github.com/open-mmlab/OpenUnReID/blob/master/tools/CycleGAN/config.yaml#L69

另外，iters是跟显存无关的

**Comment by GJTNB** [comment]
非常感谢，可以了。
