### ISSUE TITLE
Question about Reliable Clusters

### ISSUE THREAD

**Issue by Youskrpig** [open-mmlab/OpenUnReID#18]
Hi,  Have you tried adding the condition of learning with reliable Clusters( independence of clusters and compactness of clusters)  directly based on MMT ?

**Comment by yxgeee** [comment]
I did not try it, you can run it by simply modify the `eps` in the config file.
However, MMT will prevent all the outliers from being used for training, resulting in less training samples after applying the reliable criterion, so I am not sure whether the reliable criterion would boost MMT.

**Comment by Youskrpig** [comment]
Thanks a lot.  I will try
