### ISSUE TITLE
Market1501->Duck,单GPU可以汇报下么？

### ISSUE THREAD

**Issue by muzishen** [open-mmlab/OpenUnReID#29]
非常感谢你们优秀的开源项目！
当我用单GPU去复现时，batchsize设置64，其他没有任何改变，
Market1501->Duck, mAP=64.5%,Rank1=79.3%。 
我不清楚单GPU为何差这么多，你们有试过单GPU的性能么？

**Comment by yxgeee** [comment]
你好，我没试过单卡。ReID中BN的batchsize会影响最终的性能，比方说，四卡跑bs=64，那BN的bs就是16，换成单卡的话，虽然bs还是64，但BN的bs就是64了，所以区别在这里。或许你可以尝试减小bs去跑，但是lr可能需要相应去调整。Good luck!

**Comment by muzishen** [comment]
> 
> 
> 你好，我没试过单卡。ReID中BN的batchsize会影响最终的性能，比方说，四卡跑bs=64，那BN的bs就是16，换成单卡的话，虽然bs还是64，但BN的bs就是64了，所以区别在这里。或许你可以尝试减小bs去跑，但是lr可能需要相应去调整。Good luck!

回复的很及时，非常感谢！
