### ISSUE TITLE
Question on SPCL+

### ISSUE THREAD

**Issue by Terminator8758** [open-mmlab/OpenUnReID#3]
Hi, i notice that on the given leaderboard, SPCL+ shows higher performance than SPCL on both unsupervised and UDA re-id task. What's the main difference between SPCL and SPCL+ that brings the performance boost? Thanks ~

**Comment by yxgeee** [comment]
Hi, the main upgrade is that we adopt GeM pooling to replace the average pooling in the network (refer to https://github.com/open-mmlab/OpenUnReID/blob/master/tools/SpCL/config.yaml#L8).

**Comment by Terminator8758** [comment]
Ok, thanks!
