### ISSUE TITLE
关于num_parts的问题

### ISSUE THREAD

**Issue by chongyangwang-song** [open-mmlab/OpenUnReID#45]
您好，在config中是可以设置num_parts的，但是代码里似乎是在对channel做划分，而不是对特征谱做分条。不知道我理解的对不对，求解答

**Comment by Jacobxz** [comment]
解决了？

**Comment by chongyangwang-song** [comment]
仔细研究下代码，改一改。就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月8日(周一) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [open-mmlab/OpenUnReID] 关于num_parts的问题 (#45)




 
解决了？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chongyangwang-song** [comment]
你在用OpenUnReID吗，可以交流下吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/OpenUnReID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 晚上11:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/OpenUnReID] 关于num_parts的问题 (#45)





 
解决了？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
