### ISSUE TITLE
您好，有两个小问题。

### ISSUE THREAD

**Issue by huang1997214** [open-mmlab/OpenUnReID#8]
1.您好config里的iters，可以理解成每个epoch拿出iters个mini-batch用于train吗?
2.对于大规模数据(几十万张图),bybird memory内存开销过大这个问题，您有什么解决的思路吗?

麻烦您啦!

**Comment by yxgeee** [comment]
1. 是的；
2. 现在hybrid memory是存在GPU上的，如果数据量过大，可以存在CPU上，但是速度会变慢。

**Comment by huang1997214** [comment]
谢谢您的回复!
针对第一个问题,您论文里好像是用全部的数据，但是代码里只拿出若干个iters的mini-batch。想问下您为何这么处理呢？

**Comment by yxgeee** [comment]
论文里可能忘记细说这里了，这边一直是这么处理的，因为source和target的图片数量不同，所以我就手动设置了iteration数量。这个iteration数量一定程度上影响cluster更新的速度，实验试过200/400/800，我发现duke/market这种小一点的数据集400比较好，msmt这种比较大的数据集800比较好。

**Comment by huang1997214** [comment]
感谢您的解答，谢谢您!
