### ISSUE TITLE
关于大规模数据的问题

### ISSUE THREAD

**Issue by huang1997214** [open-mmlab/OpenUnReID#9]
对于ReIDtask,在数据规模较大(source20万,target40万)的时候，计算jaccard_distance的时候出现memory error。(loss的计算已经放到cpu,内存128GB)
![WeChat Work Screenshot_20200824221854](https://user-images.githubusercontent.com/45142783/91055907-de0a9480-e657-11ea-92e2-b9c7f67cc67e.png)
因为对您的代码还不是太熟悉,想问下您在计算loss的时候,不用矩阵乘法,一个batch一个batch的计算是否能解决这个问题呢?
此外您觉得还有哪些地方可以进一步优化呢?
谢谢您啦!

**Comment by yxgeee** [comment]
请问计算jaccard_distance选择的也是CPU是吗？

**Comment by huang1997214** [comment]
实在抱歉,config里TRAIN.PSEUDO_LABELS.search_type还是0，我改成3再试一下。

**Comment by yxgeee** [comment]
不过看样子不是faiss_gpu的问题。看你报错的这句话，是numpy在cpu上的memory error。如果是这样的话，感觉得重新优化一下矩阵存储和运算这块了。我再琢磨一下。

**Comment by yxgeee** [comment]
是不是你把loss放在cpu上占用了太多cpu内存，导致这里的numpy无法计算？你尝试先把loss等放回到gpu上呢？然后jaccard这边search_option选3，看看gpu或者cpu会不会超内存。

**Comment by huang1997214** [comment]
谢谢您的回复!我再试试看看。

**Comment by huang1997214** [comment]
谢谢您的回复!我再试试看看。

**Comment by huang1997214** [comment]
您好，我后来发现内存大部分是用在dbscan计算dist(N * N)。我感觉这里是否可以进行优化,只选取top-K个node。即把N * N压缩成N * topk。

**Comment by huang1997214** [comment]
您好,之前内存超都是由于准备dbscan时需要保存dist(N * N) 。是否可在此进行优化,对于每个节点只考察top-K个节点而不是全部节点(N * top-K) 牺牲一定的精度及时间换取空间。

**Comment by yxgeee** [comment]
其实现在就是只考虑top-k1的，可能写代码的方法上可以进行优化。那个N*N的矩阵很大一部分都是1，都是top-k1以外的。但是dbscan的输入需要是一个N*N的similarity矩阵，所以我觉得可以尝试分chunk做。把你的数据分成几个部分，分别做聚类。如果聚类后不做后处理（将几个部分的聚类label合理合并）的话，需要牺牲一定的精度，因为几个部分之间的样本无法相互比较。

Yifeng <notifications@github.com>于2020年8月25日 周二16:59写道：

**Comment by huang1997214** [comment]
我现在在尝试重写一下dbscan，之后再改一下compactness以及independenc(那里也构造了N * N)。谢谢您之前的帮助！
